import numpy as np
from scipy.linalg import block_diag

from src.model.r0_generator_base import R0GeneratorBase


class R0SirModel(R0GeneratorBase):
    """
    Age-structured SIR model used for computing the basic reproduction number (R_0)
    via the next-generation matrix (NGM) approach.
    """

    def __init__(self, param: dict, n_age: int = 17, country: str = "usa") -> None:
        """
        :param dict param: Dictionary of epidemiological model parameters.
        :param int n_age: Number of age groups.
        :param str country: Label identifying the model variant or data source.
        """
        self.country = country
        state = ["i"]
        super().__init__(param=param, states=state, n_age=n_age)

        self._get_e()
        self._get_v()

    def _get_v(self) -> np.ndarray:
        """
        Constructs the V matrix for the next-generation formulation.
        V represents transition out of infectious compartments.
        For a single-state SIR model, this corresponds to recovery.

        The matrix is block-diagonal across age groups:
            V_{i,i} = alpha_i  (removal/recovery rate)

        :return np.ndarray: The V matrix
        """
        idx = self._idx
        v = np.zeros((self.n_age * self.n_states,
                      self.n_age * self.n_states))

        # Infectious individuals leave compartment "i" at rate alpha_i
        v[idx("i"), idx("i")] = self.parameters["alpha_i"]

        # Precompute inverse of V for the NGM calculation
        self.v_inv = np.linalg.inv(v)

    def _get_f(self, cm: np.ndarray) -> np.ndarray:
        """
        Constructs the F matrix for the next-generation formulation.
        F represents new infections generated by each infectious individual

        :param np.ndarray cm: Age-structured contact matrix of shape (n_age, n_age) representing per-capita contacts.
        :return np.ndarray: The F matrix
        """
        i = self.i  # state-index mapping for "i"
        s_mtx = self.s_mtx  # offset for shifting between age groups in flat indexing
        n_state = self.n_states

        f = np.zeros((self.n_age * n_state,
                      self.n_age * n_state))

        # susceptibility column vector (n_age, 1)
        susc_vec = self.parameters["susc"].reshape((-1, 1))

        # Fill F:
        # F[age_a, age_b] = susceptibility(age_a) * contacts(from age_b to age_a)

        # cm.T used because transmission flows from infectors in age_b to susceptibles in age_a.
        f[i["i"]:s_mtx:n_state, i["i"]:s_mtx:n_state] = cm.T * susc_vec

        return f

    def _get_e(self):
        """
        Constructs the "e" vector, which selects exposed/initially infected states
        for the NGM calculation.
        """
        block = np.zeros(self.n_states)
        block[0] = 1  # mark infectious state

        # Start with the first age group
        self.e = block

        # Block-diagonal replication for all age groups
        for _ in range(1, self.n_age):
            self.e = block_diag(self.e, block)
